MESSAGES = {
    'en': {
        'start': 'Hello! I am your TikTok and Instagram monitoring bot. Please choose an option from the menu below.',
        'welcome_new_user': 'Welcome! I\'ve detected your language is English. You can change it anytime in settings.',
        'language_changed': 'Language changed to English.',
        'choose_platform': 'Please choose the platform you want to monitor:',
        'enter_profile_url': 'Please send me the public profile URL (e.g., https://www.tiktok.com/@username or https://www.instagram.com/username).',
        'invalid_url': 'That doesn\'t look like a valid TikTok or Instagram profile URL. Please try again.',
        'profile_added': 'Successfully added {platform} profile for monitoring: {username}. I will notify you of changes.',
        'profile_already_added': 'This profile is already being monitored.',
        'profile_removed': 'Profile {username} has been removed from monitoring.',
        'no_profiles_to_remove': 'You don\'t have any profiles to remove.',
        'select_profile_to_remove': 'Select the profile you want to remove:',
        'monitoring_paused': 'Monitoring for {username} has been paused.',
        'monitoring_resumed': 'Monitoring for {username} has been resumed.',
        'no_active_monitoring': 'You don\'t have any active monitoring sessions.',
        'select_profile_to_pause_resume': 'Select the profile to pause/resume monitoring:',
        'report_header': '📊 Monitoring Report for {username} ({platform}) 📊\n\n',
        'followers_count': 'Followers: {count}',
        'following_count': 'Following: {count}',
        'new_followers': '✨ New Followers: {count}\n{list}',
        'unfollowers': '💔 Unfollowers: {count}\n{list}',
        'possible_blockers': '🚫 Possible Blockers: {count}\n{list}',
        'no_changes': 'No significant changes detected since last check.',
        'last_checked': 'Last checked: {last_checked}',
        'checking_now': 'Checking {platform} profile {username} now... This might take a moment.',
        'report_on_demand_success': 'Report generated successfully!',
        'error_generating_report': 'An error occurred while generating the report. Please try again later.',
        'settings_menu': '⚙️ Settings:\nChoose an option:',
        'choose_language': 'Choose your preferred language:',
        'language_selection': 'Language Selection',
        'back_to_main_menu': 'Back to Main Menu',
        'main_menu': 'Main Menu',
        'no_profiles_monitored': 'You are not monitoring any profiles yet. Use "Add Profile" to start.',
        'error_occured': 'An unexpected error occurred. Please try again later.',
        'profile_not_found': 'Profile not found or inaccessible. Please check the URL and try again.',
        'processing_request': 'Processing your request...', 
        'select_action': 'Please select an action:',
        'add_profile': '➕ Add Profile',
        'get_latest_report': '📊 Get Latest Report',
        'check_now': '🔁 Check Now',
        'pause_monitoring': '🔕 Pause Monitoring',
        'remove_account': '🗑️ Remove Account',
        'settings': '⚙️ Settings',
        'tiktok': 'TikTok',
        'instagram': 'Instagram',
        'confirm_remove': 'Are you sure you want to remove {username} from monitoring?',
        'yes': 'Yes',
        'no': 'No',
        'confirm_pause': 'Are you sure you want to pause monitoring for {username}?',
        'confirm_resume': 'Are you sure you want to resume monitoring for {username}?',
        'status_active': 'Active',
        'status_paused': 'Paused',
        'current_status': 'Current Status: {status}',
        'profile_details': 'Profile: {username}\nPlatform: {platform}\nStatus: {status}',
        'select_profile_for_report': 'Select a profile to get its latest report:',
        'select_profile_for_check': 'Select a profile to check now:',
        'admin_menu': '👑 Admin Menu:\nManage monitoring accounts.',
        'add_monitoring_account': '➕ Add Monitoring Account',
        'list_monitoring_accounts': '📋 List Monitoring Accounts',
        'remove_monitoring_account': '🗑️ Remove Monitoring Account',
        'not_authorized': '🚫 You are not authorized to access this feature.',
        'enter_mon_account_platform': 'Enter the platform for the new monitoring account (tiktok/instagram):',
        'enter_mon_account_username': 'Enter the username for the new monitoring account:',
        'enter_mon_account_password': 'Enter the password for the new monitoring account:',
        'mon_account_login_failed': 'Failed to log in with the provided credentials. Please check them and try again.',
        'mon_account_added_success': 'Monitoring account {username} ({platform}) added successfully and cookies saved!',
        'mon_account_add_failed': 'Failed to add monitoring account. Please try again.',
        'no_monitoring_accounts': 'No monitoring accounts found.',
        'select_mon_account_to_remove': 'Select a monitoring account to remove:',
        'confirm_remove_mon_account': 'Are you sure you want to remove monitoring account {username} ({platform})?',
        'mon_account_removed': 'Monitoring account {username} ({platform}) removed successfully.',
        'mon_account_remove_failed': 'Failed to remove monitoring account.',
        'mon_account_list_header': '📋 Current Monitoring Accounts:\n\n',
        'mon_account_details': 'ID: {id}\nPlatform: {platform}\nUsername: {username}\nActive: {active}\nLast Used: {last_used}\nCookies: {cookies_status}\n',
    },
    'ar': {
        'start': 'أهلاً بك! أنا بوت مراقبة حسابات تيك توك وإنستغرام. الرجاء اختيار خيار من القائمة أدناه.',
        'welcome_new_user': 'مرحباً! لقد اكتشفت أن لغتك هي العربية. يمكنك تغييرها في أي وقت من الإعدادات.',
        'language_changed': 'تم تغيير اللغة إلى العربية.',
        'choose_platform': 'الرجاء اختيار المنصة التي ترغب في مراقبتها:',
        'enter_profile_url': 'الرجاء إرسال رابط الملف الشخصي العام (مثال: https://www.tiktok.com/@username أو https://www.instagram.com/username).',
        'invalid_url': 'لا يبدو هذا رابط ملف شخصي صالح لتيك توك أو إنستغرام. الرجاء المحاولة مرة أخرى.',
        'profile_added': 'تمت إضافة ملف {platform} الشخصي للمراقبة بنجاح: {username}. سأقوم بإعلامك بأي تغييرات.',
        'profile_already_added': 'هذا الملف الشخصي تتم مراقبته بالفعل.',
        'profile_removed': 'تمت إزالة ملف {username} الشخصي من المراقبة.',
        'no_profiles_to_remove': 'ليس لديك أي ملفات شخصية لإزالتها.',
        'select_profile_to_remove': 'اختر الملف الشخصي الذي تريد إزالته:',
        'monitoring_paused': 'تم إيقاف المراقبة لـ {username}.',
        'monitoring_resumed': 'تم استئناف المراقبة لـ {username}.',
        'no_active_monitoring': 'ليس لديك أي جلسات مراقبة نشطة.',
        'select_profile_to_pause_resume': 'اختر الملف الشخصي لإيقاف/استئناف المراقبة:',
        'report_header': '📊 تقرير المراقبة لـ {username} ({platform}) 📊\n\n',
        'followers_count': 'المتابعون: {count}',
        'following_count': 'يتابع: {count}',
        'new_followers': '✨ متابعون جدد: {count}\n{list}',
        'unfollowers': '💔 غير متابعين: {count}\n{list}',
        'possible_blockers': '🚫 حظر محتمل: {count}\n{list}',
        'no_changes': 'لم يتم الكشف عن تغييرات كبيرة منذ آخر فحص.',
        'last_checked': 'آخر فحص: {last_checked}',
        'checking_now': 'جاري فحص ملف {platform} الشخصي {username} الآن... قد يستغرق هذا بعض الوقت.',
        'report_on_demand_success': 'تم إنشاء التقرير بنجاح!',
        'error_generating_report': 'حدث خطأ أثناء إنشاء التقرير. الرجاء المحاولة مرة أخرى لاحقاً.',
        'settings_menu': '⚙️ الإعدادات:\nاختر خياراً:',
        'choose_language': 'اختر لغتك المفضلة:',
        'language_selection': 'اختيار اللغة',
        'back_to_main_menu': 'العودة إلى القائمة الرئيسية',
        'main_menu': 'القائمة الرئيسية',
        'no_profiles_monitored': 'أنت لا تراقب أي ملفات شخصية بعد. استخدم "إضافة ملف شخصي" للبدء.',
        'error_occured': 'حدث خطأ غير متوقع. الرجاء المحاولة مرة أخرى لاحقاً.',
        'profile_not_found': 'لم يتم العثور على الملف الشخصي أو يتعذر الوصول إليه. الرجاء التحقق من الرابط والمحاولة مرة أخرى.',
        'processing_request': 'جاري معالجة طلبك...', 
        'select_action': 'الرجاء اختيار إجراء:',
        'add_profile': '➕ إضافة ملف شخصي',
        'get_latest_report': '📊 الحصول على آخر تقرير',
        'check_now': '🔁 فحص الآن',
        'pause_monitoring': '🔕 إيقاف المراقبة مؤقتاً',
        'remove_account': '🗑️ إزالة حساب',
        'settings': '⚙️ الإعدادات',
        'tiktok': 'تيك توك',
        'instagram': 'إنستغرام',
        'confirm_remove': 'هل أنت متأكد أنك تريد إزالة {username} من المراقبة؟',
        'yes': 'نعم',
        'no': 'لا',
        'confirm_pause': 'هل أنت متأكد أنك تريد إيقاف المراقبة لـ {username} مؤقتاً؟',
        'confirm_resume': 'هل أنت متأكد أنك تريد استئناف المراقبة لـ {username}؟',
        'status_active': 'نشط',
        'status_paused': 'متوقف مؤقتاً',
        'current_status': 'الحالة الحالية: {status}',
        'profile_details': 'الملف الشخصي: {username}\nالمنصة: {platform}\nالحالة: {status}',
        'select_profile_for_report': 'اختر ملفًا شخصيًا للحصول على أحدث تقرير له:',
        'select_profile_for_check': 'اختر ملفًا شخصيًا للفحص الآن:',
        'admin_menu': '👑 قائمة المسؤول:',
        'add_monitoring_account': '➕ إضافة حساب مراقبة',
        'list_monitoring_accounts': '📋 قائمة حسابات المراقبة',
        'remove_monitoring_account': '🗑️ إزالة حساب مراقبة',
        'not_authorized': '🚫 أنت غير مصرح لك بالوصول إلى هذه الميزة.',
        'enter_mon_account_platform': 'أدخل المنصة لحساب المراقبة الجديد (tiktok/instagram):',
        'enter_mon_account_username': 'أدخل اسم المستخدم لحساب المراقبة الجديد:',
        'enter_mon_account_password': 'أدخل كلمة المرور لحساب المراقبة الجديد:',
        'mon_account_login_failed': 'فشل تسجيل الدخول باستخدام بيانات الاعتماد المقدمة. الرجاء التحقق منها والمحاولة مرة أخرى.',
        'mon_account_added_success': 'تمت إضافة حساب المراقبة {username} ({platform}) بنجاح وحفظ الكوكيز!',
        'mon_account_add_failed': 'فشل إضافة حساب المراقبة. الرجاء المحاولة مرة أخرى.',
        'no_monitoring_accounts': 'لم يتم العثور على حسابات مراقبة.',
        'select_mon_account_to_remove': 'اختر حساب مراقبة لإزالته:',
        'confirm_remove_mon_account': 'هل أنت متأكد أنك تريد إزالة حساب المراقبة {username} ({platform})؟',
        'mon_account_removed': 'تمت إزالة حساب المراقبة {username} ({platform}) بنجاح.',
        'mon_account_remove_failed': 'فشل إزالة حساب المراقبة.',
        'mon_account_list_header': '📋 حسابات المراقبة الحالية:\n\n',
        'mon_account_details': 'المعرف: {id}\nالمنصة: {platform}\nاسم المستخدم: {username}\nنشط: {active}\nآخر استخدام: {last_used}\nالكوكيز: {cookies_status}\n',
    }
}

def get_message(lang_code: str, key: str, **kwargs) -> str:
    return MESSAGES.get(lang_code, MESSAGES["en"]).get(key, f"Error: Message key {key} not found for {lang_code}").format(**kwargs)


