
from telegram.ext import ConversationHandler

class States:
    MAIN_MENU = 0
    ADD_PROFILE_PLATFORM = 1
    ADD_PROFILE_URL = 2
    REMOVE_PROFILE_CONFIRM = 3
    PAUSE_RESUME_PROFILE_CONFIRM = 4
    GET_REPORT_SELECT_PROFILE = 5
    CHECK_NOW_SELECT_PROFILE = 6
    SETTINGS_MENU = 7
    SELECT_LANGUAGE = 8

    # Admin States
    ADMIN_MENU = 9
    ADD_MON_ACCOUNT_PLATFORM = 10
    ADD_MON_ACCOUNT_USERNAME = 11
    ADD_MON_ACCOUNT_PASSWORD = 12
    REMOVE_MON_ACCOUNT_SELECT = 13
    REMOVE_MON_ACCOUNT_CONFIRM = 14


